### ISSUE TITLE
ID_check 함수의 구현 및 실행 방향에 대해서 

### ISSUE THREAD

**Issue by taeminkim-408** [oss2023miniproject/Hiddink_check#1]
ID_check 함수구현

**Comment by kimbbanggyu** [comment]
ID_Check 함수구현
조건 : 학번을 입력받는데, 자릿 수는 8자리여야 되고, 앞에 두자리는 10부터 23까지만 받는다. 
만일 조건에 부합하면 위에 프로그램은 실행을 멈춘다.

**Comment by taeminkim-408** [comment]
함수 구현
int idcheck(){
    int input;

    while(1){
        printf("\n당신의 학번을 입력해주세요: ");
        scanf("%d",&input);
        if(input >= 11111111 && input <= 24000000){
            break;
        }
        else{
            printf("학번이 맞지 않습니다. 다시 입력하시길 바랍니다.\n ");
    }
}
    return input;
}
@@ 추가사항 각 id별로 섹션을 저장할지 생각해야 할 것 같습니다.
