### ISSUE TITLE
현재 구현해야 될 기능들 

### ISSUE THREAD

**Issue by kimbbanggyu** [oss2023miniproject/Hiddink_check#11]
1. 팀의 예약 시간을 시간 단위가 아니라 분 단위로 받아서 사용하기
2. 상대하고 싶은 팀 찾기
3. 메뉴 기능을 만들어서 대표적으로 6개로 나누기 (인원 찾기, 현재 운동장 예약한 팀 보기, 팀 예약 취소 수정 메뉴, 인원 및 다른 팀 찾기, 파일 저장하기, 종료) 
4. 파일에 저장하는데 어떻게 저장할 것인가?(이것은 이야기 필요!)
5. 그리고 팀을 수정하거나 삭제할 때 자신의 학번이 아니라면 삭제하거나 수정할 수 없게 만들기

확인하시고 여기서 더 필요한 기능이 있으면 말씀해주세요. ㅎㅎ

**Comment by taeminkim-408** [comment]
1. 팀의 예약 시간을 시간 단위가 아니라 분 단위로 받아서 사용하기
     - 처리했습니다. 하지만 구조체를 변경해야 합니다. 일단 제 임의대로 한번 변경해보겠습니다.
2. 이건 오늘 내로 처리할 예정입니다.
3이거는 만나서 이야기를 해야 할 것 같습니다.
5. 수정을 했는데 현재 삭제 함수가 2개가 있습니다. 이 부분에 대해서는 논의 거쳐야 할 것 같습니다.

**Comment by kimbbanggyu** [comment]
확인했습니다.
