### ISSUE TITLE
경기장 예약을 시간에서 분으로 바꾸면

### ISSUE THREAD

**Issue by kimbbanggyu** [oss2023miniproject/Hiddink_check#12]
만약에 시간을 분으로 바꾸면 코드를 조금씩 다 바꿔야 될 것 같습니다. 
구조체 Team의 인덱스 크기를 24개로 하고 미리 데이터를 할당했습니다.
그리고 제가 만든 예약 함수들을 보면 인덱스 접근할 때 Team안에 있는 starttime으로 접근하고 있습니다. 
하지만 만약에 starttime에 시간이 아닌 분으로 저장을 한다면 모든 함수에 있는 것을 조금씩 다 고쳐야 되는데 혹시 괜찮으실까요?

**Comment by taeminkim-408** [comment]
현재 그 부분을 전부 수정했습니다. 
일단 구조체 부분에서 전부 수정을 했는데 이 부분에 대해서는 한번 이야기를 해봐야 할 것 같습니다.
typedef struct{
    char name [100];  //대표자 이름
    int playground; //0일 경우 평봉, 1일 경우 히딩크
    int teamname[100];  //팀이름
    int countnumber;  //팀 전체 인원
    int studentnumber;
} Person;

typedef struct {
    int starttime;
    int endtime;
    char teamname [100];
    char name[100];
    int student_number;
} Team;

현재 만들어진 2개의 구조체입니다. person은 현재 수정된 상태입니다. 일단 struct을 하나로 합치는 것 부터 시작을 해야할 것 같습니다.

**Comment by kimbbanggyu** [comment]
넵 그러면 오늘 모여서 확인해보고 
마지막으로 수정할 것 정하고 코드를 완성하면 될 것 같습니다.
