### ISSUE TITLE
메뉴판 정리 

### ISSUE THREAD

**Issue by taeminkim-408** [oss2023miniproject/Hiddink_check#13]
현재 메뉴판에서 출력이 되고 있는 상황입니다. 
*** FOOTBALL CHECK SYSTEM ***
1. 경기장 조회
2. 경기장 예약
3. 예약 수정
4. 예약 삭제
5. 파일저장
6. 이름검색
7. 현재 경기장 예약 현황 조회
8. 팀으로 예약하기
9. 팀 예약취소하기
0. 종료

일단 팀으로 예약과 경기장으로 예약이 너무 겹치는 것이 많다고 생각합니다. 이 부분에 대해서 일단 조정을 해야 할 것 같습니다.

**Comment by taeminkim-408** [comment]
저는 로그아웃 기능을 추가하는 것도 나쁘지 않을 것 같습니다.

**Comment by kimbbanggyu** [comment]
로그아웃 기능을 추가하는 것도 나쁘지 않을 것 같습니다.

**Comment by taeminkim-408** [comment]
1. 경기장 조회
2. 경기장 예약
3. 예약 수정
4. 예약 삭제
5. 파일저장
6. 이름검색
7. 현재 경기장 예약 현황 조회
8. 팀으로 예약하기
9. 팀 예약취소하기
10. 로그아웃 
11. 시스템 종료
