### ISSUE TITLE
상대방 팀을 찾는 옵션중에서 삭제함수 버그발생

### ISSUE THREAD

**Issue by kimbbanggyu** [oss2023miniproject/Hiddink_check#16]
그 상대방 팀을 찾는 옵션 중에서 삭제 함수에 버그가 발생했는데 무엇이 잘못됐는지 모르겠습니다.
delete 함수에서 인덱스를 지우고 난 다음에 다시 추가 할려고 할 때 
인덱스의 값이 달라져서 문제점이 발생하더라구요.
혹시 확인 한번 해주실 수 있나요?
delete함수는 제 이름 branch의 함수파일에 있습니다.

**Comment by taeminkim-408** [comment]
수정완료
