### ISSUE TITLE
풋볼 예약 시스템을 할 때 어떤식으로 접근을 해야하고 어떤식으로 구성을 해야 하는지에 대해서 

### ISSUE THREAD

**Issue by taeminkim-408** [oss2023miniproject/Hiddink_check#4]
1. 리스트 출력을 할 때 시간표를 추출할지 아니면 사람마다 구성을 나오게 만들지 

2. 파일 저장을 할때 어떤식으로 만들어야할지

3.해당 파일의 구체화

**Comment by taeminkim-408** [comment]
1. 
_________________________
시간   |   사람  |   인원   | 장소
________________________
시간   |   사람  |   인원   | 장소
이런식으로 구현
2. 시간, 사람 인원 장소 순으로 구현
3. 파일 저장 후 불러오는 값을 정렬로 구현하면 될 것 같습니다. 

파일 구체화 해서 아래에 만들기

**Comment by kimbbanggyu** [comment]
택스트 파일에서 읽오는 것은 이런식으로 하면 될것 같습니다. 
그리고 현재 저희가 히딩크 경기장과 평봉필드 두개의 예약 시스템이니깐 2개의 텍스트 파일을 만들어야 될거 같아요.
만약에 사용자가 평봉필드를 이용하겠다. 하면은 평봉필드 택스트 파일을 읽어오고,
만약에 히딩크 경기장을 이용하겠다 하면은 히딩크 택스트 파일을 읽어오도록 코드를 짜면 어떨 까요?

**Comment by kimbbanggyu** [comment]
lab과 main을 이용해서 위에 기능을 넣었습니다. 실행은 잘됩니다.
