### ISSUE TITLE
팀을 예약시스템에서 넣는 방법

### ISSUE THREAD

**Issue by kimbbanggyu** [oss2023miniproject/Hiddink_check#6]
지금 코드에서는 인원수를 구할 수 있도록 하는 코드만 나와있습니다.
하지만 저희는 예약시스템이니깐 팀을 저장하는 기능을 만들어야 됩니다.
그래서 구조체를 2개 만들면 어떨까요?
하나의 구조체는 축구를 하고 싶어하는 사람의 정보.
또 다른 구조체에서는 현재 어떠한 팀이 예약했는지 확인하는 정보

typedef sturct{
    int time [14]; // 9시부터 11시까지 예약한 시간을 나타내는 변수
    char teamname [100]; // 팀의 이름을 나타내는 변수
    string name[11]; // 팀원의 이름을 저장하는 변수(최대 11명으로한다.)
}이것은 예약한 팀을 저장하는 struct입니다.

확인하시고 struct에 대해서 문제가 있다면 말씀해주세요!

**Comment by taeminkim-408** [comment]
typedef sturct{
int time [14]; // 9시부터 11시까지 예약한 시간을 나타내는 변수 
->시간을 저장한다면 24:00를 최대로 하는 것을 기준으로 처음 시작값과 끝나는 값을 만들면 될 것 같습니다. 
char teamname [100]; // 팀의 이름을 나타내는 변수
string name[11]; // 팀원의 이름을 저장하는 변수(최대 11명으로한다.)
-> 이 부분이 이해가 가지 않는데 각 선수의 이름을 전부 넣는 것으로 할려고 하는 건지 아니면 한사람의 이름을 넣을려고 하는 건 지 잘 모르겠습니다. 
}이것은 예약한 팀을 저장하는 struct입니다.

typedef sturct{
int startime [4]; // 몇시: 몇분 이런식으로 4개의 값만 넣으면 될 것 같습니다.  
int endtime[4]; // 몇시:몇분인지 넣으면 될 것 같습니다.
char teamname [100]; // 팀의 이름을 나타내는 변수
string name[11]; // 저는 개인적으로 대표자의 이름만 추가하면 될 것 같습니다. 
int wantpeople; // 해당 값은 예약자가 원하는 선수의 숫자입니다. 
}

**Comment by kimbbanggyu** [comment]
아 넵 저도 코딩하다가 보니 팀원의 대표자 한명만 넣으면 되는데 왜 굳이 다 같이 넣을려고 했는지 저 조차도 의문이 생겼네요;;; 제가 잘못했습니다.

그래서 struct의 name이라는 것에 그냥 string이 아닌 char 형태로 넣어도 될거 같습니다.

한 팀이 시간을 무제한으로 이용하는 것을 방지해서 시작 시간과 끝나는 시간을 입력 받는데 한 팀이 최대한으로 빌릴 수 있는 시간이 한 시간으로 정하는 것은 어떨까요? (시작 시간과 끝나는 시간은 반드시 시간 단위로 받는 것은 어떨까요? ex : 7시 8시)
