### ISSUE TITLE
lab1.c에 예약하는 함수만들었습니다. 하지만 아직 완벽하게 작동하지 않습니다.

### ISSUE THREAD

**Issue by kimbbanggyu** [oss2023miniproject/Hiddink_check#8]
lab1.c에 팀을 예약하는 함수 4개를 만들었지만 아직 완벽하게 작동하지 않습니다. 완성하면 label을 bug에서 documentation으로 고치겠습니다. 보시고 혹시 고칠 부분이 있으시면 말씀해주세요. ㅎㅎ
예약하는 코드 예시입니다.(아직 미완성).
#include <stdio.h>
#include <stdlib.h>
#include <time.h> 
#include <string.h> 
#include "main.h" 

int reserveTime(Team *t[]){ //이것은 적절한 시간으로 빌렸는지 확인하는 함수입니다.
    int startTime;
    int endTime;
    int count=0;
    while(1){
    printf("빌리고 싶은 시작 시간를 입력하세요(오후 5시는 17시로 입력!) : ");
    scanf("%d",&startTime);
    printf("\n끝나는 시간을 입력하세요(오후 6시는 18시로 입력!) : ");
    scanf("%d",&endTime);

    if(endTime - startTime  == 1) {
        t[startTime]->starttime = startTime;//t[start]에 넣은 것은 예약한 사람을 확인하는데 시간별로 확인하기 위해서 이렇게 사용했습니다.
        break;
    }

    else printf("\n빌리는 시간이 적절하지 않습니다. 다시 입력해주세요! : ");
    }
    return startTime;    
}

void reserveteamName(Team *t[],int time){
    char teamName[100];
    char teamLeader[100];

    printf("\n빌리는 팀 이름을 입력해주세요! : ");
    scanf("%[^\n]s",teamName);
    printf("\n대표자의 이름을 입력해주세요! : ");
    getchar();
    scanf("%[^\n]s",teamLeader);

    for(int i=0; i<24; i++){
        if(!strcmp(teamName,t[i]->teamname)) {
            printf("\n이미 빌린 팀입니다.\n");
            t[time]->starttime = 0;
            t[time]->endtime = 0;
            printf("자동적으로 예약시스템이 취소 후 종료됩니다.\n");
            return;
        }
        if(!strcmp(teamLeader,t[i]->name)) {
            printf("\n이미 빌린 사람입니다.\n");
            t[time]->starttime = 0;
            t[time]->endtime = 0;
            printf("자동적으로 예약시스템이 취소 후 종료됩니다.\n");
            return;
        }

    }
    strcpy(t[time]->teamname,teamName);
    strcpy(t[time]->name,teamLeader);    
}

void reserveSystem(Team **t){
    int number = reserveTime(t);
    reserveteamName(t,number);
}

void teamfillmethod(Team **t){ //team의 사이즈를 먼저 늘리기 이유 : 예약을 조회할 때 nullptr이라면 그 시간은 비어있다고 생각
    for(int i=0; i<24; i++){
        t[i] = (Team*)malloc(sizeof(Team));
    }
}

**Comment by taeminkim-408** [comment]
int reserveTime(Team *t[]){ //이것은 적절한 시간으로 빌렸는지 확인하는 함수입니다.
     int startTime;
     int endTime;
     int count=0;
     while(1){
          printf("빌리고 싶은 시작 시간를 입력하세요(오후 5시는 17시로 입력!) : ");
          scanf("%d",&startTime);
          printf("\n끝나는 시간을 입력하세요(오후 6시는 18시로 입력!) : ");
          scanf("%d",&endTime);
          if(endTime - startTime  == 1) {
              t[startTime]->starttime = startTime;//t[start]에 넣은 것은 예약한 사람을 확인하는데 시간별로 확인하기 위해서 이렇게 사용했습니다.
              break;
          }
    else printf("\n빌리는 시간이 적절하지 않습니다. 다시 입력해주세요! : ");
}
          return startTime;    
}

일단 보내주신 코드 reserveTime에서 받아들이는 시간을 시단위로 받을 것인지 정해야 할 것 같습니다. 해당 질문에서 가독성을 높여야 할것 같아서 질문을 수정하고 분단위까지 받는 걸 목표로 만들어 보겠습니다. 해당 부분은 문자여롤 변경하는 것이 좋을 것 같습니다. 

int reserveTime(Team *t[]){ //이것은 적절한 시간으로 빌렸는지 확인하는 함수입니다.
    char input;
    char input2;
    int starttime[1];
    int endtime[1];

    int startTime;
    int endTime;
    int count=0;
    int check=0;

    while(1){
   
            printf("빌리고 싶은 시작 시간를 입력하세요(오후 5시는 17시로 입력!) : ");
            scanf("%s",&input);
            char *ptr = strtok(&input, ":");      // " " 공백 문자를 기준으로 문자열을 자름, 포인터 반환
            check=0;
            while (ptr != NULL){     
                starttime[check]= atoi(ptr);        //문자열 자르기 
                ptr = strtok(NULL, " "); 
                check++;     
        }
           
        printf("\n끝나는 시간을 입력하세요(오후 6시는 18시로 입력!) : ");
        scanf("%s",&input);
        char *ptr2 = strtok(&input, ":");      // " " 공백 문자를 기준으로 문자열을 자름, 포인터 반환
        check=0;
        while (ptr != NULL){     
            endtime[check]= atoi(ptr2);        //문자열 자르기 
            ptr = strtok(NULL, " "); 
            check++;     
        }

        if(t[startTime]->starttime == startTime) printf("\n그 시간엔 이미 사용자가 있습니다.\n");
        else if(endTime - startTime  == 1) {
            t[startTime]->starttime = startTime;//t[start]에 넣은 것은 예약한 사람을 확인하는데 시간별로 확인하기 위해서 이렇게 사용했습니다.
            t[startTime]->endtime = endTime; 
            break;
        }
        else printf("\n빌리는 시간이 적절하지 않습니다. 다시 입력해주세요!\n");
    }
    return startTime;    
}

해당 코드는 일단 일단 분까지는 받지만 struct구조를 변경해야 할 거 같습니다.
