### ISSUE TITLE
메인을 인원찾기, 팀 예약 및 취소하기, 다른 팀 찾기으로 세분화 및 서로 연결될 수 있게 구현하기!

### ISSUE THREAD

**Issue by kimbbanggyu** [oss2023miniproject/Hiddink_check#9]
현재 저희 기능을 보면 인원 찾기(완성함), 팀 예약 및 취소(file 입,출력만 만들면 된다.), 다른 팀 찾기(진행중)가 대표적으로 나뉘는 기능인데,
이 3가지를 대표로 해 놓고, 사용자가 원하는 항목이 있다면 그 항목으로 이동하게 만들어서 사용자가 원하는 항목의 기능을 이용하도록 만들고, 만약에 이렇게 진행하다가 다른 항목으로 넘어가고 싶다면 1. 메인으로 돌아가기, 2. 원하는 항목으로 넘어가기(이것은 대표적인 기능을 하는 함수 3개를 만들어야 될거 같다. => 그냥 함수 이름을 만들고 그 함수안에 세부적인 기능 첨가 :쉽게 만들 수 있음) -> 이런식으로 좀 더 정갈하게 만들면 어떨까요?

만약에 괜찮다면 1.메인으로 돌아가기와   2. 원하는 항목으로 넘어가기 어떨까요?
이 의견에 대해서 어떻게 생각하는지 말씀해 주세요

**Comment by taeminkim-408** [comment]
재대로 이해를 했는지 모르겠지만

메뉴 -> 원하는 메뉴 -> 해당 항목에서 원래 메뉴로 복귀 이렇게 이야기 하시는 것 같습니다.

현재상황에서는 일단 함수 구현을 전부 마치고 하는게 더 좋을 것 같습니다.
